name: reader-snap
base: core18
version: '0.1dev'
summary: A test snap to read configs from another snap
description: |
  A test snap to read configs from another snap

grade: devel
confinement: devmode

parts:
  reader-snap:
    # See 'snapcraft plugins'
    source: .
    plugin: python
    requirements: ['requirements.txt']

plugs:
  shared-files:
    interface: content
    content: shared-files
    target: $SNAP_COMMON
    #default-provider: writer-snap:shared-files

apps:
  reader-snap:
    command: reader-snap
